framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - assets/vendor/select2  # <-- Ajoute cette ligne si nécessaire
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
